use_frameworks!

platform :ios, '10.3'

target 'Apple-Cocoapod-KochavaAdNetwork_Example' do
  pod 'Apple-Cocoapod-KochavaAdNetwork', :path => '../'

  target 'Apple-Cocoapod-KochavaAdNetwork_Tests' do
    inherit! :search_paths

    
  end
end
